// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoryById(ctx context.Context, id int32) (Category, error)
	GetCategoryByTitle(ctx context.Context, title string) (Category, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	GetUserByName(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
